name: pv_smart_click
description: "Aplikacija za izracun optimalnog solarnog potencijala"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  #state management
  flutter_bloc: ^8.1.3
  #comparing dart objects
  equatable: ^2.0.5
  #service locator
  get_it: ^7.6.7
  #make request to api
  retrofit: ^4.0.3
  http: ^1.2.0
  #Hooks
  flutter_hooks: ^0.20.4
  #dateFormat
  intl: ^0.19.0
  #chached image
  cached_network_image: ^3.3.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: 8.0.6
  build_runner: 2.4.8
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/vectors/icons/dark_blue/
    - assets/vectors/icons/light_blue/
    - assets/vectors/icons/light_yellow/
    - assets/vectors/icons/navigation/
    - assets/vectors/icons/social/
    - assets/vectors/logo/
    - assets/vectors/photo/
    - assets/3a.json
    - lib/features/
    - lib/features/data/
    - lib/features/presentation/
    - lib/features/presentation/pages/
    - lib/features/presentation/widgets/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/barlow/Barlow-Black.ttf
        - asset: assets/fonts/barlow/Barlow-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/barlow/Barlow-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/barlow/Barlow-Medium.ttf
          weight: 400
        - asset: assets/fonts/barlow/Barlow-Regular.ttf
          weight: 500
